import type { StockListItem } from '@/lib/types';

/**
 * VITE_USE_MOCK=true 일 때만 쓰는 종목 목록. 실제 응답은 GET /api/stocks 이다.
 * 백엔드 MVP 고정 목록(app/core/mvp_stocks.py)과 같은 100개, 시가총액 순위 순.
 */


export const mockStockListAsOf = '2026-10-04T12:00:00+09:00';

export const mockStockList: StockListItem[] = [
  { rank: 1, code: '005930', name: '삼성전자', market: 'KOSPI', sector: '전기전자' },
  { rank: 2, code: '000660', name: 'SK하이닉스', market: 'KOSPI', sector: '전기전자' },
  { rank: 3, code: '005935', name: '삼성전자우', market: 'KOSPI', sector: '전기전자' },
  { rank: 4, code: '402340', name: 'SK스퀘어', market: 'KOSPI', sector: '금융' },
  { rank: 5, code: '009150', name: '삼성전기', market: 'KOSPI', sector: '전기전자' },
  { rank: 6, code: '373220', name: 'LG에너지솔루션', market: 'KOSPI', sector: '전기전자' },
  { rank: 7, code: '005380', name: '현대차', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 8, code: '207940', name: '삼성바이오로직스', market: 'KOSPI', sector: '제약' },
  { rank: 9, code: '105560', name: 'KB금융', market: 'KOSPI', sector: '금융' },
  { rank: 10, code: '032830', name: '삼성생명', market: 'KOSPI', sector: '보험' },
  { rank: 11, code: '028260', name: '삼성물산', market: 'KOSPI', sector: '유통' },
  {
    rank: 12,
    code: '012450',
    name: '한화에어로스페이스',
    market: 'KOSPI',
    sector: '운송장비·부품',
  },
  { rank: 13, code: '034020', name: '두산에너빌리티', market: 'KOSPI', sector: '기계·장비' },
  { rank: 14, code: '055550', name: '신한지주', market: 'KOSPI', sector: '금융' },
  { rank: 15, code: '329180', name: 'HD현대중공업', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 16, code: '000270', name: '기아', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 17, code: '006400', name: '삼성SDI', market: 'KOSPI', sector: '전기전자' },
  { rank: 18, code: '068270', name: '셀트리온', market: 'KOSPI', sector: '제약' },
  { rank: 19, code: '034730', name: 'SK', market: 'KOSPI', sector: '금융' },
  { rank: 20, code: '086790', name: '하나금융지주', market: 'KOSPI', sector: '금융' },
  { rank: 21, code: '066570', name: 'LG전자', market: 'KOSPI', sector: '전기전자' },
  { rank: 22, code: '012330', name: '현대모비스', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 23, code: '010120', name: 'LS ELECTRIC', market: 'KOSPI', sector: '전기전자' },
  { rank: 24, code: '035420', name: 'NAVER', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 25, code: '000810', name: '삼성화재', market: 'KOSPI', sector: '보험' },
  { rank: 26, code: '298040', name: '효성중공업', market: 'KOSPI', sector: '전기전자' },
  { rank: 27, code: '042700', name: '한미반도체', market: 'KOSPI', sector: '기계·장비' },
  { rank: 28, code: '096770', name: 'SK이노베이션', market: 'KOSPI', sector: '화학' },
  { rank: 29, code: '316140', name: '우리금융지주', market: 'KOSPI', sector: '금융' },
  { rank: 30, code: '005490', name: 'POSCO홀딩스', market: 'KOSPI', sector: '금속' },
  { rank: 31, code: '267260', name: 'HD현대일렉트릭', market: 'KOSPI', sector: '전기전자' },
  { rank: 32, code: '042660', name: '한화오션', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 33, code: '009540', name: 'HD한국조선해양', market: 'KOSPI', sector: '금융' },
  { rank: 34, code: '010130', name: '고려아연', market: 'KOSPI', sector: '금속' },
  { rank: 35, code: '000150', name: '두산', market: 'KOSPI', sector: '전기전자' },
  { rank: 36, code: '138040', name: '메리츠금융지주', market: 'KOSPI', sector: '금융' },
  { rank: 37, code: '011200', name: 'HMM', market: 'KOSPI', sector: '운송·창고' },
  { rank: 38, code: '015760', name: '한국전력', market: 'KOSPI', sector: '전기·가스' },
  { rank: 39, code: '017670', name: 'SK텔레콤', market: 'KOSPI', sector: '통신' },
  { rank: 40, code: '010950', name: 'S-Oil', market: 'KOSPI', sector: '화학' },
  { rank: 41, code: '051910', name: 'LG화학', market: 'KOSPI', sector: '화학' },
  { rank: 42, code: '033780', name: 'KT&G', market: 'KOSPI', sector: '음식료·담배' },
  { rank: 43, code: '010140', name: '삼성중공업', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 44, code: '006800', name: '미래에셋증권', market: 'KOSPI', sector: '증권' },
  { rank: 45, code: '018260', name: '삼성에스디에스', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 46, code: '003550', name: 'LG', market: 'KOSPI', sector: '금융' },
  { rank: 47, code: '079550', name: 'LIG디펜스앤에어로스페이스', market: 'KOSPI', sector: '금속' },
  { rank: 48, code: '003670', name: '포스코퓨처엠', market: 'KOSPI', sector: '전기전자' },
  { rank: 49, code: '024110', name: '기업은행', market: 'KOSPI', sector: '금융' },
  { rank: 50, code: '267250', name: 'HD현대', market: 'KOSPI', sector: '금융' },
  { rank: 51, code: '272210', name: '한화시스템', market: 'KOSPI', sector: '전기전자' },
  { rank: 52, code: '086280', name: '현대글로비스', market: 'KOSPI', sector: '운송·창고' },
  { rank: 53, code: '035720', name: '카카오', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 54, code: '278470', name: '에이피알', market: 'KOSPI', sector: '화학' },
  { rank: 55, code: '011070', name: 'LG이노텍', market: 'KOSPI', sector: '전기전자' },
  { rank: 56, code: '030200', name: 'KT', market: 'KOSPI', sector: '통신' },
  { rank: 57, code: '047810', name: '한국항공우주', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 58, code: '000720', name: '현대건설', market: 'KOSPI', sector: '건설' },
  { rank: 59, code: '064350', name: '현대로템', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 60, code: '005830', name: 'DB손해보험', market: 'KOSPI', sector: '보험' },
  { rank: 61, code: '003490', name: '대한항공', market: 'KOSPI', sector: '운송·창고' },
  { rank: 62, code: '307950', name: '현대오토에버', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 63, code: '443060', name: 'HD현대마린솔루션', market: 'KOSPI', sector: '일반서비스' },
  { rank: 64, code: '071050', name: '한국금융지주', market: 'KOSPI', sector: '금융' },
  { rank: 65, code: '047050', name: '포스코인터내셔널', market: 'KOSPI', sector: '유통' },
  { rank: 66, code: '005940', name: 'NH투자증권', market: 'KOSPI', sector: '증권' },
  { rank: 67, code: '078930', name: 'GS', market: 'KOSPI', sector: '금융' },
  { rank: 68, code: '000500', name: '가온전선', market: 'KOSPI', sector: '전기전자' },
  { rank: 69, code: '323410', name: '카카오뱅크', market: 'KOSPI', sector: '금융' },
  { rank: 70, code: '028050', name: '삼성E&A', market: 'KOSPI', sector: '일반서비스' },
  { rank: 71, code: '006260', name: 'LS', market: 'KOSPI', sector: '금융' },
  { rank: 72, code: '259960', name: '크래프톤', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 73, code: '003230', name: '삼양식품', market: 'KOSPI', sector: '음식료·담배' },
  { rank: 74, code: '0126Z0', name: '삼성에피스홀딩스', market: 'KOSPI', sector: '금융' },
  { rank: 75, code: '007660', name: '이수페타시스', market: 'KOSPI', sector: '전기전자' },
  { rank: 76, code: '180640', name: '한진칼', market: 'KOSPI', sector: '금융' },
  { rank: 77, code: '009830', name: '한화솔루션', market: 'KOSPI', sector: '화학' },
  { rank: 78, code: '016360', name: '삼성증권', market: 'KOSPI', sector: '증권' },
  { rank: 79, code: '090430', name: '아모레퍼시픽', market: 'KOSPI', sector: '화학' },
  { rank: 80, code: '161390', name: '한국타이어앤테크놀로지', market: 'KOSPI', sector: '화학' },
  { rank: 81, code: '353200', name: '대덕전자', market: 'KOSPI', sector: '전기전자' },
  { rank: 82, code: '047040', name: '대우건설', market: 'KOSPI', sector: '건설' },
  { rank: 83, code: '021240', name: '코웨이', market: 'KOSPI', sector: '일반서비스' },
  { rank: 84, code: '064400', name: 'LG씨엔에스', market: 'KOSPI', sector: 'IT 서비스' },
  { rank: 85, code: '062040', name: '산일전기', market: 'KOSPI', sector: '전기전자' },
  { rank: 86, code: '000880', name: '한화', market: 'KOSPI', sector: '화학' },
  { rank: 87, code: '039490', name: '키움증권', market: 'KOSPI', sector: '증권' },
  { rank: 88, code: '352820', name: '하이브', market: 'KOSPI', sector: '오락·문화' },
  { rank: 89, code: '128940', name: '한미약품', market: 'KOSPI', sector: '제약' },
  { rank: 90, code: '032640', name: 'LG유플러스', market: 'KOSPI', sector: '통신' },
  { rank: 91, code: '001440', name: '대한전선', market: 'KOSPI', sector: '전기전자' },
  { rank: 92, code: '000990', name: 'DB하이텍', market: 'KOSPI', sector: '전기전자' },
  { rank: 93, code: '005387', name: '현대차2우B', market: 'KOSPI', sector: '운송장비·부품' },
  { rank: 94, code: '326030', name: 'SK바이오팜', market: 'KOSPI', sector: '일반서비스' },
  { rank: 95, code: '267270', name: 'HD건설기계', market: 'KOSPI', sector: '기계·장비' },
  { rank: 96, code: '000100', name: '유한양행', market: 'KOSPI', sector: '제약' },
  { rank: 97, code: '377300', name: '카카오페이', market: 'KOSPI', sector: '금융' },
  { rank: 98, code: '175330', name: 'JB금융지주', market: 'KOSPI', sector: '금융' },
  { rank: 99, code: '241560', name: '두산밥캣', market: 'KOSPI', sector: '기계·장비' },
  { rank: 100, code: '011790', name: 'SKC', market: 'KOSPI', sector: '화학' },
];
